[package]
name = "trobble-rs"
version = "0.1.0"
authors = ["Joshua Hawxwell <m@hawx.me>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
failure = "0.1.1"
num_cpus = "1.8"
r2d2 = "0.8.2"
r2d2_sqlite = "0.6"
rusqlite = "0.14"
